### ISSUE TITLE
Criação de Types

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/main#35]
A criação de Types reflete os models, criação de mais Types desnecessariamente podem desorganizar a estrutura e deixar mais difícil de compreender

Já existe o model de Livro e já existe o model de Versao. Para que criar outro Type? O certo seria...

![image](https://user-images.githubusercontent.com/34348097/228992404-a8003b80-3713-4433-b304-ee5d60d4db49.png)

![image](https://user-images.githubusercontent.com/34348097/228992004-7d20b071-0d8c-4d54-b256-abbb49e348c3.png)

O mesmo acontece, por exemplo, com 

![image](https://user-images.githubusercontent.com/34348097/228992466-f75b096e-afbb-4f03-a461-7fc0fd211958.png)

Perceba que usuário já tem perguntas dentro de si pelo relacionamento de tabelas

![image](https://user-images.githubusercontent.com/34348097/228992587-8d0fb83c-7862-496a-ace5-c034d7246e82.png)

Dessa forma seria melhor que o Type fosse o próprio `Usuario`

```js
usuario {
    perguntas {
        blablabla
   }
}
```

**Comment by Ckk3** [comment]
Quanto a primeira parte, reduzir os Types, irei testar se consigo encontrar uma maneira de retornar um type com os outros dados necessários.
Já a segunda parte, as perguntas não estao listadas no usuario, mas sim, as perguntas possuem o id do usuário que a criou. Sendo assim, o model usuário por padrão não tem as perguntas, logo, eu tenho que fazer uma busca de todas as perguntas com o id do usuario. Irei tentar mesclar a as perguntas dessa busca direto no type do User.

**Comment by Ckk3** [comment]
Consegui mesclar as perguntas no UserType, também reduzir o TextoBiblico para usar o TypeVersiculo.
Irei fechar a issue

**Comment by filiperochalopes** [comment]
Na verdade o model usuário contém sim a referencia de `perguntas_criadas` fazer essa busca adicional pelo id trás verbosidade ao projeto já, que é algo que já tem nativo, sugiro que retorne as alterações e faça pelo método padrão! Para compreender melhor o que acontece, observe os `related_names` [na documentação](https://docs.djangoproject.com/en/4.1/ref/models/fields/).

Ao criar o model de perguntas e adicionar o link com User ele automaticamente faz uma referencia reversa com o nome do `related_name`. Compreender agora?

![image](https://user-images.githubusercontent.com/34348097/229284461-1b6ba95c-cd2f-4e0a-b2b3-f204ca776453.png)

**Comment by Ckk3** [comment]
![image](https://user-images.githubusercontent.com/62259205/229334493-29082f10-85a4-4670-913d-49af74a7036a.png)
No meu projeto os verbose names estão diferente, mas consegui entender o funcionamento sem nenhum problema. Irei alterar e implementar .

**Comment by Ckk3** [comment]
Implementado, irei fechar Issue

**Comment by filiperochalopes** [comment]
Não foi observada a primeira parte da issue, demos duas atividades nessa issue, apenas a última foi realizada. E sobre a criação de Types com livroAbreviado, que não é atributo de nenhum `model`.  Repito então qual seria a abordagem:

```txt
textoBiblico(referencia:String!){
  versiculo {
    capitulo
    versiculo
    texto
    livro {
      nome
      sigla
    }
    versao {
      nome
      sigla
    }
  }
}

**Comment by Ckk3** [comment]
Erro meu, irei corrigir

**Comment by Ckk3** [comment]
Corrigido!
