### ISSUE TITLE
Sobre o idioma de variáveis

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/main#36]
Em #31 comento que, para manter o padrão manteremos as variáveis em português, mas vejo no código uma mescla de português e inglês que me deixa um pouco confuso e com aspecto de bagunçado, favor alterar. Veja um exemplo:

![image](https://user-images.githubusercontent.com/34348097/228992995-d698e784-126d-406d-ac88-51de75c38b62.png)

**Comment by Ckk3** [comment]
Erro meu, irei corrigir

**Comment by Ckk3** [comment]
Fiz a alteração das variáveis e algumas funções para português, mantive somente aquele que precisam ser inglês para funcionar ou os campos dos models que são em ingles, por exemplo: `password `no campo `user`

**Comment by Ckk3** [comment]
Corrigido, irei fechar a issue

**Comment by filiperochalopes** [comment]
É, de fato, tem alguns que vem do django e não conseguimos mudar. Essas devem persistir.
