### ISSUE TITLE
Pasta pages

### ISSUE THREAD

**Issue by filiperochalopes** [Jogo-da-Biblia/main#37]
Existe uma pasta `pages`que não entendi o motivo

![image](https://user-images.githubusercontent.com/34348097/228993174-8cedf5d5-0282-45fa-95dc-a2c08071a6b6.png)

**Comment by Ckk3** [comment]
Eu não adicionei essa pasta, ela é herdada da branch develop. 
https://github.com/Jogo-da-Biblia/main/tree/develop/cadastro_perguntas/app/app/pages

**Comment by filiperochalopes** [comment]
Pode remover. Como o projeto foi te dado para fazer a parte do graphQLAPI, tudo que tiver nessa branch deve ser só isso. Pode excluir pacotes, arquivos e pastas que não estejam sendo utilizados em seu projeto. Grato.

**Comment by Ckk3** [comment]
Ok, irei fazer isso

**Comment by Ckk3** [comment]
Pasta removida!
